chore: refactor error capturing

diff --git a/.github/workflows/using-action.yml b/.github/workflows/using-action.yml
--- a/.github/workflows/using-action.yml
+++ b/.github/workflows/using-action.yml
@@ -25,8 +25,11 @@ jobs:
 
       - name: Run Cypress Tests with LambdaTest
         run: |
-          npx lambdatest-cypress run
-          if [ $? -ne 0 ]; then
-            echo "Tests failed"
-            exit 1
+          # Run Cypress tests
+          output=$(npx lambdatest-cypress run)
+          echo "$output"
+          # Check for failures in the output
+          if echo "$output" | grep -q "failed"; then
+          echo "Tests failed"
+          exit 1
           fi
